### ISSUE TITLE
Feature Request: Expose it as a swift package

### ISSUE THREAD

**Issue by rodrigoelp** [kieranb662/PartitionKit#1]
With the advent of Swift Package Manager (SPM) included in XCode 11, it would be amazing to have this code as a package/framework to easily include it in your project.

Description on how to set it up is [available here](https://www.raywenderlich.com/1993018-an-introduction-to-swift-package-manager#toc-anchor-002)

**Comment by rodrigoelp** [comment]
I might be able to contribute on this ;)

**Comment by rodrigoelp** [comment]
Scratch that... I just noticed the package.swift file... silly me :|

**Comment by kieranb662** [comment]
Haha its all good dude
