### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kaishin** [kieranb662/PartitionKit#2]
Please think of adding a license so that this can be used by others.

Quoting [opensource.org](https://opensource.org/faq#approved-licenses-only):

> Can I call my program "Open Source" even if I don't use an approved license?
Please don't do that. If you call it "Open Source" without using an approved license, you will confuse people. This is not merely a theoretical concern — we have seen this confusion happen in the past, and it's part of the reason we have a formal license approval process. See also our page on license proliferation for why this is a problem.

**Comment by rafaga** [comment]
Please @kieranb662 define a License on the project

**Comment by kieranb662** [comment]
I added the license. Thanks again!
