### ISSUE TITLE
Define a version on this package to properly use as Swift Package

### ISSUE THREAD

**Issue by rafaga** [kieranb662/PartitionKit#3]
I'm having problems using your package as version range in Xcode, checking the repo I'm observing that you don't have define any tag on the repo, and XCode use this as version identifier.

I'm asking you to define a version number (0.0.0) to mark the initial release (for development) and permit us to use it in Xcode as Version Range. Thanks

**Comment by kieranb662** [comment]
Just added a license and a package version. Thank you for your patience.
